- clean: ['~']

- link:
    ~/.axelrc: axelrc
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.rtorrent.rc: rtorrent.rc
    ~/.sbt/0.13/build.sbt:
      create: true
      path: sbt/0.13/build.sbt
    ~/.sbt/0.13/plugins/plugins.sbt:
      create: true
      path: sbt/0.13/plugins/plugins.sbt
    ~/.screenrc: screenrc
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.zsh: zsh/
    ~/.zshrc: zshrc

- shell:
  -
    - mkdir -p ~/.rtorrent/session ~/.rtorrent/watch ~/.rtorrent/downloads
    - Creating rtorrent directories
  -
    - git update-submodules
    - Installing/updating submodules
